service: todo-list-api

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  stage: dev
  memorySize: 128
  timeout: 180

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY